name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Required to create and upload releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Required for goreleaser to generate a changelog

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26'
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
